const data = {
  products: [
    {
      _id: "1",
      name: "Haggar",
      category: " Khaki Flat",
      image: "/images/p1.jpg",
      price: 120.99,
      countInStock: 10,
      brand: "Nike",
      rating: 4.5,
      numReviews: 160,
      description:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque nisl eros, pulvinar facilisis justo mollis, auctor consequat urna. Morbi a bibendum metus. Donec scelerisque sollicitudin enim eu venenatis. Duis tincidunt laoreet",
    },
    {
      _id: "2",
      name: "Wrangler",
      category: "Jeans",
      image: "/images/p2.jpg",
      price: 100.85,
      countInStock: 20,
      brand: "Adidas",
      rating: 4.0,
      numReviews: 210,
      description:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque nisl eros, pulvinar facilisis justo mollis, auctor consequat urna. Morbi a bibendum metus. Donec scelerisque sollicitudin enim eu venenatis. Duis tincidunt laoreet",
    },
    {
      _id: "3",
      name: "Southpole",
      category: "Jogger Fleece Pants",
      image: "/images/p3.jpg",
      price: 221.99,
      countInStock: 0,
      brand: "Lacoste",
      rating: 4.8,
      numReviews: 170,
      description:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque nisl eros, pulvinar facilisis justo mollis, auctor consequat urna. Morbi a bibendum metus. Donec scelerisque sollicitudin enim eu venenatis. Duis tincidunt laoreet",
    },
    {
      _id: "4",
      name: "Dickies",
      category: "Work Pant",
      image: "/images/p4.jpg",
      price: 79.99,
      countInStock: 15,
      brand: "Nike",
      rating: 4.5,
      numReviews: 142,
      description:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque nisl eros, pulvinar facilisis justo mollis, auctor consequat urna. Morbi a bibendum metus. Donec scelerisque sollicitudin enim eu venenatis. Duis tincidunt laoreet",
    },
    {
      _id: "5",
      name: "Vineyard Vines",
      category: "Straight Leg Pants",
      image: "/images/p5.jpg",
      price: 65.75,
      countInStock: 5,
      brand: "Puma",
      rating: 4.5,
      numReviews: 140,
      description:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque nisl eros, pulvinar facilisis justo mollis, auctor consequat urna. Morbi a bibendum metus. Donec scelerisque sollicitudin enim eu venenatis. Duis tincidunt laoreet",
    },
    {
      _id: "6",
      name: "Dockers",
      category: "Khaki Pant",
      image: "/images/p6.jpg",
      price: 139.12,
      countInStock: 12,
      brand: "Adidas",
      rating: 4.5,
      numReviews: 515,
      description:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque nisl eros, pulvinar facilisis justo mollis, auctor consequat urna. Morbi a bibendum metus. Donec scelerisque sollicitudin enim eu venenatis. Duis tincidunt laoreet",
    },
    {
      _id: "7",
      name: "Casio FX",
      category: "Watch",
      image: "/images/watch1.jpg",
      price: 199.95,
      countInStock: 12,
      brand: "Casio",
      rating: 4.9,
      numReviews: 154,
      description:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque nisl eros, pulvinar facilisis justo mollis, auctor consequat urna. Morbi a bibendum metus. Donec scelerisque sollicitudin enim eu venenatis. Duis tincidunt laoreet",
    },
    {
      _id: "8",
      name: "Casio WCS",
      category: "Watch",
      image: "/images/men-s-casio-2.jpg",
      price: 199.99,
      countInStock: 12,
      brand: "Casio",
      rating: 4.9,
      numReviews: 715,
      description:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque nisl eros, pulvinar facilisis justo mollis, auctor consequat urna. Morbi a bibendum metus. Donec scelerisque sollicitudin enim eu venenatis. Duis tincidunt laoreet",
    },
    {
      _id: "9",
      name: "Casio PX",
      category: "Watch",
      image: "/images/watch1.jpg",
      price: 399.85,
      countInStock: 12,
      brand: "Casio",
      rating: 4.9,
      numReviews: 365,
      description:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque nisl eros, pulvinar facilisis justo mollis, auctor consequat urna. Morbi a bibendum metus. Donec scelerisque sollicitudin enim eu venenatis. Duis tincidunt laoreet",
    },
    {
      _id: "10",
      name: "Casio XH3",
      category: "Watch",
      image: "/images/men-s-casio-2.jpg",
      price: 299.95,
      countInStock: 12,
      brand: "Casio",
      rating: 4.9,
      numReviews: 655,
      description:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque nisl eros, pulvinar facilisis justo mollis, auctor consequat urna. Morbi a bibendum metus. Donec scelerisque sollicitudin enim eu venenatis. Duis tincidunt laoreet",
    },
    {
      _id: "11",
      name: "Casio FX9",
      category: "Watch",
      image: "/images/watch1.jpg",
      price: 459.95,
      countInStock: 62,
      brand: "Casio",
      rating: 5,
      numReviews: 2542,
      description:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque nisl eros, pulvinar facilisis justo mollis, auctor consequat urna. Morbi a bibendum metus. Donec scelerisque sollicitudin enim eu venenatis. Duis tincidunt laoreet",
    },
    {
      _id: "12",
      name: "Casio XH3",
      category: "Watch",
      image: "/images/men-s-casio-2.jpg",
      price: 219.95,
      countInStock: 82,
      brand: "Casio",
      rating: 4.9,
      numReviews: 655,
      description:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque nisl eros, pulvinar facilisis justo mollis, auctor consequat urna. Morbi a bibendum metus. Donec scelerisque sollicitudin enim eu venenatis. Duis tincidunt laoreet",
    },
  ],
};
export default data;
